# Generated by Django 4.2.3 on 2023-09-08 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eitaa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='token',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
